/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractMyjsonSemanticSequencer;

@SuppressWarnings("all")
public class MyjsonSemanticSequencer extends AbstractMyjsonSemanticSequencer {
}
