/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractMyjsonSyntacticSequencer;

@SuppressWarnings("all")
public class MyjsonSyntacticSequencer extends AbstractMyjsonSyntacticSequencer {
}
