/**
 * generated by Xtext
 */
package org.xtext.example.yaml.serializer;

import org.xtext.example.yaml.serializer.AbstractMyDslSyntacticSequencer;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractMyDslSyntacticSequencer {
}
